import pandas as pd
import matplotlib.pyplot as plt

dfg = pd.read_excel("students_info.xlsx")
#print(dfg)
dfr = pd.read_html("results_ejudge.html")
#print(dfr[0])
df = pd.merge(dfg, dfr[0], left_on=["login"], right_on=["User"])
#print(df)
faculty = df.groupby("group_faculty")["Solved"].mean()
print(faculty)
out = df.groupby("group_out")["Solved"].mean()
print(out)
faculty.plot(kind="bar")
plt.xticks(rotation=0)
plt.title("Среднее количество решённых задач по факультетским группам")
plt.savefig("faculty.jpg")
out.plot(kind="bar")
plt.xticks(rotation=0)
plt.title("Среднее количество решённых задач по новым группам")
plt.savefig("out.jpg")
GH = (df[(df['G'] > 10) | (df['H'] > 10)])
faculty_gh = GH["group_faculty"].unique()
out_gh = GH["group_out"].unique()
print(GH)
print("Факультетские группы:", *faculty_gh)
print("Группы по информатике:", *out_gh)